elasticSearch:
  host: elasticsearch
kubernetes:
  host: https://kubernetes.default
fluentd:
  namespace: tools
  image:
    name: stakater/fluentd-kubernetes
    tag: "0.14.25-1.1"
    pullPolicy: IfNotPresent