elasticSearch:
  host: elasticsearch
  port: 9200
kubernetes:
  host: https://kubernetes.default
fluentd:
  labels:
    version: "1.2.0-1.1.0"
    group: com.stakater.platform
    provider: stakater
  namespace: tools
  image:
    name: stakater/fluentd-kubernetes
    tag: "1.2.0-1.1.0"
    pullPolicy: IfNotPresent
  config:
    # configPath: 
    templates:
      fluent.conf: |-
        # Listen for logs on port 24224 of docker host network, as pod runs with HostNetwork: true
        # (docker log driver will send to this address)
        <source>
          @type forward
          port 24224
        </source>

        # Read kubernetes logs
        <source>
          @type tail
          path /var/log/containers/*.log
          pos_file /var/log/es-containers.log.pos
          time_format %Y-%m-%dT%H:%M:%S.%N
          tag kubernetes.*
          format json
          read_from_head true
        </source>

        <filter kubernetes.var.log.containers.**.log>
          @type kubernetes_metadata
        </filter>

        # TODO: This regex is incomplete at the moment. 
        # # Springboot default Java Stacktrace filter
        # <filter **>
        #   @type concat
        #   key log
        #   multiline_start_regexp /^(?<time>\d{4}-\d{1,2}-\d{1,2} \d{1,2}:\d{1,2}:\d{1,2}.\d{1,3})[\s]*(?<level>[^\s]+) (?<pid>[\d]+) --- \[(?<thread>.*)\] (?<class>[^\s]+)[\s]*:[\s]*(?<message>.*)/
        # </filter>

        # Generic multiline (for docker containers)
        # TODO: add multiline_end_regexp, as without that, multiline logs won't be 
        # parsed by concat filter if another log doesn't come immedietly after that one
        # see https://github.com/fluent-plugins-nursery/fluent-plugin-concat/issues/2
        <filter **>
          @type concat
          key log
          multiline_start_regexp /^[\S]+/
          flush_interval 30s
        </filter>

        # Send all logs to ES
        <match **>
          @type elasticsearch
          @log_level info
          include_tag_key true
          host elasticsearch
          port 9200
          logstash_format true
          # For EK 6+ setup
          # logstash_prefix logs
          flush_interval 30s
          # Never wait longer than 5 minutes between retries.
          max_retry_wait 60
          # Disable the limit on the number of retries (retry forever).
          disable_retry_limit
          time_key timestamp
          reload_connections false
        </match>