---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    annotations:
      fabric8.io/target-platform: kubernetes
    labels:
      chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
      release: {{ .Release.Name | quote }}
      heritage: {{ .Release.Service | quote }}
      version: {{ .Chart.Version }}
    name: {{ template "name" . }}
  data:
    fluent.conf: |-
      # Listen for logs on port 24224 of docker host network, as pod runs with HostNetwork: true
      # (docker log driver will send to this address)
      <source>
        @type forward
        port 24224
      </source>

      # Read kubernetes logs
      <source>
        @type tail
        path /var/log/containers/*.log
        pos_file /var/log/es-containers.log.pos
        time_format %Y-%m-%dT%H:%M:%S.%N
        tag kubernetes.*
        format json
        read_from_head true
      </source>

      <filter kubernetes.var.log.containers.**.log>
        @type kubernetes_metadata
      </filter>

      # Springboot default Java Stacktrace filter
      <filter **>
        @type concat
        key log
        multiline_start_regexp /^(?<time>\d{4}-\d{1,2}-\d{1,2} \d{1,2}:\d{1,2}:\d{1,2}.\d{1,3})[\s]*(?<level>[^\s]+) (?<pid>[\d]+) --- \[(?<thread>.*)\] (?<class>[^\s]+)[\s]*:[\s]*(?<message>.*)/
      </filter>

      # Generic multiline (for docker containers)
      <filter **>
        @type concat
        key log
        multiline_start_regexp /^[\S]+/
      </filter>

      # Send all logs to ES
      <match **>
        @type elasticsearch
        @log_level info
        include_tag_key true
        host elasticsearch.tools
        port 9200
        logstash_format true
        logstash_prefix logs
        flush_interval 5s
        # Never wait longer than 5 minutes between retries.
        max_retry_wait 60
        # Disable the limit on the number of retries (retry forever).
        disable_retry_limit
        time_key time
        reload_connections false
      </match>