---
apiVersion: v1
kind: List
items:
- apiVersion: extensions/v1beta1
  kind: DaemonSet
  metadata:
    annotations:
      configmap.reloader.stakater.com/reload: {{ template "fluentd.name" . }}
    labels:
{{ include "fluentd.labels.stakater" . | indent 6 }}
{{ include "fluentd.labels.chart" . | indent 6 }}
    name: {{ template "fluentd.name" . }}
  spec:
    updateStrategy:
      type: RollingUpdate
    template:
      metadata:
        annotations:
          prometheus.io/scrape: "true"
        labels:
{{ include "fluentd.labels.selector" . | indent 10 }}
      spec:
        hostNetwork: true
        dnsPolicy: ClusterFirstWithHostNet
        containers:
        - env:
          - name: ELASTICSEARCH_HOST
            value: {{ .Values.elasticSearch.host }}
          - name: ELASTICSEARCH_PORT
            value: {{ .Values.elasticSearch.port | quote }}
          - name: KUBERNETES_URL
            value: {{ .Values.kubernetes.host }}
          {{- with .Values.fluentd.config.configPath }}
          - name: FLUENTD_CONF_PATH
            value: {{ . }}
          {{- end }}
          image: "{{ .Values.fluentd.image.name }}:{{ .Values.fluentd.image.tag }}"
          imagePullPolicy: {{ .Values.fluentd.image.pullPolicy }}
          name: fluentd
          ports:
          - containerPort: 24231
            name: scrape
          - containerPort: 24224
            hostPort: 24224
          resources:
            limits:
              cpu: 100m
          securityContext:
            privileged: true
          volumeMounts:
          - mountPath: /var/log
            name: varlog
          - mountPath: /var/lib/docker/containers
            name: defaultdocker
            readOnly: true
          - mountPath: /mnt/ephemeral/docker/containers
            name: awsdocker
            readOnly: true
          - mountPath: /mnt/sda1/var/lib/docker/containers
            name: minikubedocker
            readOnly: true
          {{- if .Values.fluentd.configMap }}
          - mountPath: /etc/config/
            name: {{ template "fluentd.name" . }}
          {{- end }}
        serviceAccountName: fluentd
        # to ensure it runs on master as well
        tolerations:
          - effect: NoSchedule
            operator: Exists
        volumes:
        - hostPath:
            path: /var/log
          name: varlog
        - hostPath:
            path: /var/lib/docker/containers
          name: defaultdocker
        - hostPath:
            path: /mnt/ephemeral/docker/containers
          name: awsdocker
        - hostPath:
            path: /mnt/sda1/var/lib/docker/containers
          name: minikubedocker
        {{- if .Values.fluentd.configMap }}
        - configMap:
            name: {{ template "fluentd.name" . }}
          name: {{ template "fluentd.name" . }}
        {{- end }}