---
apiVersion: v1
kind: List
items:
- apiVersion: extensions/v1beta1
  kind: DaemonSet
  metadata:
    labels:
{{ include "labels.stakater" . | indent 6 }}
{{ include "labels.chart" . | indent 6 }}
    name: {{ template "name" . }}
  spec:
    template:
      metadata:
        annotations:
          prometheus.io/scrape: "true"
        labels:
{{ include "labels.selector" . | indent 10 }}
      spec:
        hostNetwork: true
        dnsPolicy: ClusterFirstWithHostNet
        containers:
        - env:
          - name: ELASTICSEARCH_HOST
            value: {{ .Values.elasticSearch.host }}
          - name: ELASTICSEARCH_PORT
            value: {{ .Values.elasticSearch.port | quote }}
          - name: KUBERNETES_URL
            value: {{ .Values.kubernetes.host }}
          image: "{{ .Values.fluentd.image.name }}:{{ .Values.fluentd.image.tag }}"
          imagePullPolicy: {{ .Values.fluentd.image.pullPolicy }}
          name: fluentd
          ports:
          - containerPort: 24231
            name: scrape
          - containerPort: 24224
            hostPort: 24224
          resources:
            limits:
              cpu: 100m
          securityContext:
            privileged: true
          volumeMounts:
          - mountPath: /var/log
            name: varlog
          - mountPath: /var/lib/docker/containers
            name: defaultdocker
            readOnly: true
          - mountPath: /mnt/ephemeral/docker/containers
            name: awsdocker
            readOnly: true
          - mountPath: /mnt/sda1/var/lib/docker/containers
            name: minikubedocker
            readOnly: true
          - mountPath: /fluentd/etc/
            name: fluentd-config
        serviceAccountName: fluentd
        volumes:
        - hostPath:
            path: /var/log
          name: varlog
        - hostPath:
            path: /var/lib/docker/containers
          name: defaultdocker
        - hostPath:
            path: /mnt/ephemeral/docker/containers
          name: awsdocker
        - hostPath:
            path: /mnt/sda1/var/lib/docker/containers
          name: minikubedocker
        - configMap:
            name: {{ template "name" . }}
          name: fluentd-config