apiVersion: konfigurator.stakater.com/v1alpha1
kind: KonfiguratorTemplate
metadata:
  labels:
{{ include "fluentd.labels.stakater" . | indent 6 }}
{{ include "fluentd.labels.chart" . | indent 6 }}
  name: {{ template "fluentd.name" . }}
spec:
  renderTarget: ConfigMap
  app:
    name: {{ template "fluentd.name" . }}
    kind: DaemonSet
    volumeMounts:
    - mountPath: /fluentd/etc/appconf
      container: fluentd
  templates:
    {{- range $key, $value := .Values.fluentd.config.templates }}
    {{ $key }}: |- 
{{ $value | indent 6 }}
    {{- end }}