---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    labels:
{{ include "fluentd.labels.stakater" . | indent 6 }}
{{ include "fluentd.labels.chart" . | indent 6 }}
    name: {{ template "fluentd.name" . }}

- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRole
  metadata:
    name: {{ template "fluentd.name" . }}
  rules:
  - apiGroups:
    - ""
    resources:
    - pods
    - namespaces
    verbs:
    - get
    - list
    - watch

- kind: ClusterRoleBinding
  apiVersion: rbac.authorization.k8s.io/v1beta1
  metadata:
    name: {{ template "fluentd.name" . }}
  roleRef:
    kind: ClusterRole
    name: {{ template "fluentd.name" . }}
    apiGroup: rbac.authorization.k8s.io
  subjects:
  - kind: ServiceAccount
    name: {{ template "fluentd.name" . }}
    namespace: {{ .Values.fluentd.namespace }}